In [16]:
matrix1= [
    [1,2,3],
    [4,5,6],
    [7,8,9]   
]

matrix2= [
    [1,2,3],
    [4,5,6],
    [7,8,9]   
]

result= [
    [0,0,0],
    [0,0,0],
    [0,0,0]     
]

for i in range(len(matrix1)):
    for j in range(len(matrix1[0])):
        result[i][j] = matrix1[i][j] + matrix2[i][j]

print("Matrix 1: ")        
for row in matrix1:
    print( row)
    
print("\nMatrix 2: ")
for row in matrix2:
    print( row)

print("\nAddition of these matricies: ")
for row in result:
    print( row)

Matrix 1: 
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]

Matrix 2: 
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]

Addition of these matricies: 
[2, 4, 6]
[8, 10, 12]
[14, 16, 18]


In [17]:
import numpy as np
matrix1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
result = matrix1 + matrix2
print(result)  

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
